import { useEffect, useMemo, useState } from 'react';
import { useAuth0 } from '@auth0/auth0-react';
import { Elements, PaymentElement, useElements, useStripe } from '@stripe/react-stripe-js';
import { loadStripe } from '@stripe/stripe-js';

const stripePromise=loadStripe(import.meta.env.VITE_STRIPE_PUBLISHABLE_KEY??'');
type Account={accountNumberMasked:string;serviceAddress:string;balanceCents:number;dueDate:string};
type Intent={paymentId:string;clientSecret:string;paymentIntentId:string;amountCents:number;currency:string};
type Card={id:string;brand:string;last4:string;expMonth:number;expYear:number};
type History={id:string;accountNumberMasked:string;amountCents:number;currency:string;status:string;createdAtUtc:string};

export default function WaterBillPayment({onBack}:{onBack:()=>void}){
 const {isAuthenticated,loginWithRedirect,getAccessTokenSilently}=useAuth0();
 const [accountNumber,setAccountNumber]=useState(''); const [account,setAccount]=useState<Account|null>(null); const [amount,setAmount]=useState('');
 const [intent,setIntent]=useState<Intent|null>(null); const [saveCard,setSaveCard]=useState(false); const [cards,setCards]=useState<Card[]>([]); const [selectedCard,setSelectedCard]=useState(''); const [history,setHistory]=useState<History[]>([]); const [error,setError]=useState('');
 const api=async(path:string,init?:RequestInit)=>{const token=await getAccessTokenSilently();const r=await fetch(path,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(init?.headers||{})}});const body=await r.json().catch(()=>null);if(!r.ok)throw new Error(body?.detail??'Request failed.');return body;};
 const loadProfile=async()=>{try{setCards(await api('/api/water-bills/saved-cards'));setHistory(await api('/api/water-bills/payments'));}catch{/* displayed only after a user action */}};
 useEffect(()=>{if(isAuthenticated)void loadProfile()},[isAuthenticated]);
 if(!isAuthenticated)return <main className="form-shell"><button className="back-link" onClick={onBack}>← Back</button><section className="form-card"><p className="eyebrow">Charlotte Water</p><h1>Pay your water bill</h1><p>Sign in or create a resident account to securely pay a water bill and save cards to your profile.</p><button className="primary" onClick={()=>loginWithRedirect({authorizationParams:{screen_hint:'login'}})}>Sign in to pay</button></section></main>;
 const lookup=async()=>{try{setError('');const a=await api('/api/water-bills/lookup',{method:'POST',body:JSON.stringify({accountNumber})});setAccount(a);setAmount((a.balanceCents/100).toFixed(2));setIntent(null);}catch(e){setError(e instanceof Error?e.message:'Unable to find account.')}};
 const start=async()=>{if(!account)return;try{setError('');const cents=Math.round(Number(amount)*100);const i=await api('/api/water-bills/payment-intents',{method:'POST',body:JSON.stringify({accountNumber,amountCents:cents,savePaymentMethod:saveCard,savedPaymentMethodId:selectedCard||null})});setIntent(i);}catch(e){setError(e instanceof Error?e.message:'Unable to start payment.')}};
 const options=useMemo(()=>intent?{clientSecret:intent.clientSecret,appearance:{theme:'stripe' as const}}:null,[intent]);
 return <main className="form-shell"><button className="back-link" onClick={onBack}>← Back</button><section className="form-card"><p className="eyebrow">Charlotte Water</p><h1>Pay your water bill</h1><p>Card information and wallet credentials are collected by Stripe. The CLT# application does not store card numbers or security codes.</p>{error&&<div className="alert error">{error}</div>}<div className="payment-grid"><div><label>Water account number<input value={accountNumber} onChange={e=>setAccountNumber(e.target.value)} /></label><button onClick={lookup}>Look up account</button>{account&&<div className="bill-summary"><strong>{account.accountNumberMasked}</strong><span>{account.serviceAddress}</span><span>Balance: ${(account.balanceCents/100).toFixed(2)}</span><span>Due: {account.dueDate}</span><label>Payment amount<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} /></label>{cards.length>0&&<label>Saved card (optional)<select value={selectedCard} onChange={e=>setSelectedCard(e.target.value)}><option value="">Use a new card or wallet</option>{cards.map(c=><option key={c.id} value={c.id}>{c.brand.toUpperCase()} •••• {c.last4} · {c.expMonth}/{c.expYear}</option>)}</select></label>} {!selectedCard&&<label className="check"><input type="checkbox" checked={saveCard} onChange={e=>setSaveCard(e.target.checked)}/> Save this card to my resident profile for future water payments</label>}<button className="primary" onClick={start}>Continue to payment</button></div>}</div><div>{intent&&options&&<Elements stripe={stripePromise} options={options}><Checkout intent={intent} savedPaymentMethodId={selectedCard} onDone={()=>{setIntent(null);void loadProfile()}} /></Elements>}</div></div>{history.length>0&&<section className="history"><h2>Recent water payments</h2>{history.map(h=><div className="history-row" key={h.id}><span>{h.accountNumberMasked}</span><span>${(h.amountCents/100).toFixed(2)}</span><span>{h.status}</span><span>{new Date(h.createdAtUtc).toLocaleDateString()}</span></div>)}</section>}</section></main>;
}

function Checkout({intent,savedPaymentMethodId,onDone}:{intent:Intent;savedPaymentMethodId:string;onDone:()=>void}){
 const stripe=useStripe();const elements=useElements();const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 const pay=async()=>{if(!stripe)return;setBusy(true);setMessage('');let result;if(savedPaymentMethodId){result=await stripe.confirmCardPayment(intent.clientSecret,{payment_method:savedPaymentMethodId});}else{if(!elements){setBusy(false);return;}result=await stripe.confirmPayment({elements,confirmParams:{return_url:`${window.location.origin}/?waterPayment=complete`},redirect:'if_required'});}if(result.error)setMessage(result.error.message??'Payment could not be completed.');else{setMessage('Payment submitted successfully.');onDone();}setBusy(false);};
 return <div className="stripe-box">{!savedPaymentMethodId&&<PaymentElement options={{layout:'accordion'}}/>}<button className="primary" disabled={!stripe||busy} onClick={pay}>{busy?'Processing…':'Pay securely'}</button>{message&&<p role="status">{message}</p>}<small>Apple Pay appears automatically on eligible Apple devices/browsers when enabled for this Stripe account and registered domain.</small></div>;
}
