import { useEffect, useMemo, useState } from 'react';
import { useAuth0 } from '@auth0/auth0-react';
import { serviceCatalog, serviceTitle } from './serviceCatalog';

type Scope='all'|'general'|'police'|'fire'|'airport';
type QueueItem={submissionNumber:string;serviceCode:string;department:string;receivedAtUtc:string;updatedAtUtc:string;status:string;assignedToName?:string};
type Note={createdAtUtc:string;authorName:string;text:string};
type Detail=QueueItem&{data:Record<string,unknown>;assignedToSubject?:string;submissionIpAddress?:string;submissionCountry?:string;internalNotes:Note[]};

const scopes:{id:Scope;label:string;hint:string}[]=[
 {id:'all',label:'All services',hint:'Every queue you are authorized to access'},
 {id:'general',label:'General services',hint:'Streets, neighborhoods, water, zoning, solid waste and more'},
 {id:'police',label:'Police',hint:'Restricted Police Department requests'},
 {id:'fire',label:'Fire',hint:'Restricted Fire Department requests'},
 {id:'airport',label:'Airport',hint:'Charlotte Douglas International Airport and Aviation Department requests'}
];

export default function App(){
 const {isAuthenticated,isLoading,loginWithRedirect,logout,getAccessTokenSilently,user}=useAuth0();
 const [scope,setScope]=useState<Scope>('all'); const [status,setStatus]=useState(''); const [serviceCode,setServiceCode]=useState(''); const [search,setSearch]=useState('');
 const [items,setItems]=useState<QueueItem[]>([]); const [selected,setSelected]=useState<Detail|null>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
 const apiBase=import.meta.env.VITE_EMPLOYEE_API_URL??'http://localhost:5051';
 const api=async(path:string,init?:RequestInit)=>{const token=await getAccessTokenSilently();const r=await fetch(`${apiBase}${path}`,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(init?.headers||{})}});if(!r.ok)throw new Error(r.status===403?'You do not have permission for this queue or action.':`Request failed (${r.status}).`);return r.json();};
 const load=async()=>{try{setLoading(true);setError('');const q=new URLSearchParams({scope});if(status)q.set('status',status);if(serviceCode)q.set('serviceCode',serviceCode);if(search.trim())q.set('search',search.trim());setItems(await api(`/api/requests?${q}`));}catch(e){setError(e instanceof Error?e.message:'Unable to load queue.')}finally{setLoading(false)}};
 useEffect(()=>{if(isAuthenticated)void load();},[isAuthenticated,scope,status,serviceCode]);
 const open=async(n:string)=>{try{setError('');setSelected(await api(`/api/requests/${n}`));}catch(e){setError(e instanceof Error?e.message:'Unable to load request.')}};
 const update=async(patch:object)=>{if(!selected)return;try{const d=await api(`/api/requests/${selected.submissionNumber}`,{method:'PATCH',body:JSON.stringify(patch)});setSelected(d);await load();}catch(e){setError(e instanceof Error?e.message:'Unable to update request.')}};
 const addNote=async()=>{if(!selected)return;const text=window.prompt('Internal note');if(!text)return;try{setSelected(await api(`/api/requests/${selected.submissionNumber}/notes`,{method:'POST',body:JSON.stringify({text})}));}catch(e){setError(e instanceof Error?e.message:'Unable to add note.')}};
 const visibleServices=useMemo(()=>serviceCatalog.filter(s=>scope==='all'||s.department.toLowerCase()===scope),[scope]);
 const counts=useMemo(()=>({total:items.length,received:items.filter(x=>x.status==='Received').length,active:items.filter(x=>x.status==='Assigned'||x.status==='In Progress').length,resolved:items.filter(x=>x.status==='Resolved'||x.status==='Closed').length}),[items]);
 if(isLoading)return <main className="login"><h1>Loading…</h1></main>;
 if(!isAuthenticated)return <main className="login"><p className="eyebrow">CLT# · City of Charlotte, North Carolina</p><h1>Request Operations</h1><p>Employee access only. Sign in with your City-authorized Auth0 account.</p><button onClick={()=>loginWithRedirect()}>Employee sign in</button></main>;
 return <><header><div><strong>CLT#</strong><span>Charlotte Request Operations</span></div><div className="user"><span>{user?.name??user?.email}</span><button onClick={()=>logout({logoutParams:{returnTo:window.location.origin}})}>Sign out</button></div></header><div className="layout"><aside><h2>Queues</h2>{scopes.map(s=><button key={s.id} className={scope===s.id?'active':''} title={s.hint} onClick={()=>{setSelected(null);setScope(s.id);setServiceCode('')}}>{s.label}</button>)}<label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option>Received</option><option>Assigned</option><option>In Progress</option><option>Resolved</option><option>Closed</option></select></label><label>Service<select value={serviceCode} onChange={e=>setServiceCode(e.target.value)}><option value="">All services</option>{visibleServices.map(s=><option key={s.code} value={s.code}>{s.title}</option>)}</select></label></aside><main><div className="page-title"><div><p className="eyebrow">Employee work management</p><h1>{scopes.find(s=>s.id===scope)?.label}</h1></div><button onClick={load}>Refresh</button></div><div className="metrics"><div><strong>{counts.total}</strong><span>Total</span></div><div><strong>{counts.received}</strong><span>New</span></div><div><strong>{counts.active}</strong><span>Active</span></div><div><strong>{counts.resolved}</strong><span>Completed</span></div></div><form className="searchbar" onSubmit={e=>{e.preventDefault();void load()}}><input aria-label="Search requests" placeholder="Search tracking number, service, or assignee" value={search} onChange={e=>setSearch(e.target.value)}/><button type="submit">Search</button></form>{error&&<div className="alert">{error}</div>}{selected?<DetailPanel detail={selected} onBack={()=>setSelected(null)} onUpdate={update} onAddNote={addNote}/>:loading?<p>Loading requests…</p>:<table><thead><tr><th>Tracking</th><th>Department</th><th>Service</th><th>Received</th><th>Status</th><th>Assigned</th></tr></thead><tbody>{items.map(i=><tr key={i.submissionNumber} onClick={()=>open(i.submissionNumber)}><td><button className="link">{i.submissionNumber}</button></td><td><span className={`dept ${i.department.toLowerCase()}`}>{i.department}</span></td><td>{serviceTitle(i.serviceCode)}</td><td>{new Date(i.receivedAtUtc).toLocaleString()}</td><td><span className="pill">{i.status}</span></td><td>{i.assignedToName??'Unassigned'}</td></tr>)}{!items.length&&<tr><td colSpan={6}>No requests match the selected filters.</td></tr>}</tbody></table>}</main></div></>;
}

function DetailPanel({detail,onBack,onUpdate,onAddNote}:{detail:Detail;onBack:()=>void;onUpdate:(p:object)=>void;onAddNote:()=>void}){
 const entries=useMemo(()=>Object.entries(detail.data),[detail.data]);
 return <section><button className="link" onClick={onBack}>← Back to queue</button><div className="detail-head"><div><span className={`dept ${detail.department.toLowerCase()}`}>{detail.department}</span><h2>{serviceTitle(detail.serviceCode)}</h2><p>{detail.submissionNumber}</p></div><span className="pill">{detail.status}</span></div><div className="actions"><select value={detail.status} onChange={e=>onUpdate({status:e.target.value})}><option>Received</option><option>Assigned</option><option>In Progress</option><option>Resolved</option><option>Closed</option></select><button onClick={()=>onUpdate({assignedToSubject:'self'})}>Assign to me</button><button onClick={onAddNote}>Add internal note</button></div><div className="card"><h3>Submission audit</h3><dl><div><dt>Source IP</dt><dd>{detail.submissionIpAddress??'—'}</dd></div><div><dt>Country</dt><dd>{detail.submissionCountry??'—'}</dd></div></dl></div><div className="card"><h3>Request details</h3><dl>{entries.map(([k,v])=><div key={k}><dt>{human(k)}</dt><dd>{renderValue(v)}</dd></div>)}</dl></div><div className="card"><h3>Internal notes</h3>{detail.internalNotes?.map((n,i)=><article className="note" key={i}><strong>{n.authorName}</strong><time>{new Date(n.createdAtUtc).toLocaleString()}</time><p>{n.text}</p></article>)}{!detail.internalNotes?.length&&<p>No internal notes.</p>}</div></section>
}
function human(v:string){return v.replace(/[-_]/g,' ').replace(/([A-Z])/g,' $1').replace(/\b\w/g,c=>c.toUpperCase())}
function renderValue(v:unknown){if(v===null||v===undefined||v==='')return '—';if(typeof v==='object')return <pre>{JSON.stringify(v,null,2)}</pre>;return String(v)}
