export type ServiceCatalogItem={code:string;category:string;title:string;department:string};

export const serviceCatalog:ServiceCatalogItem[]=[
  {code:'crime-report',category:'Public Safety',title:'Report a Crime (Non-Emergency)',department:'Police'},
  {code:'crime-tip',category:'Public Safety',title:'Submit a Crime Tip',department:'Police'},
  {code:'officer-commendation',category:'Public Safety',title:'Commend an Officer',department:'Police'},
  {code:'officer-misconduct',category:'Public Safety',title:'File an Officer Misconduct Complaint',department:'Police'},
  {code:'police-report-supplement',category:'Police',title:'Add Information to an Existing Police Report',department:'Police'},
  {code:'police-incident-report-copy',category:'Police',title:'Request an Incident Report',department:'Police'},
  {code:'police-crash-report-copy',category:'Police',title:'Request a Crash Report',department:'Police'},
  {code:'police-public-records',category:'Police',title:'Police Public Records Request',department:'Police'},
  {code:'police-alarm-registration',category:'Police',title:'Burglar Alarm Registration',department:'Police'},
  {code:'police-false-alarm-appeal',category:'Police',title:'False Alarm Appeal',department:'Police'},
  {code:'police-picketing-notification',category:'Police',title:'Picketing / Demonstration Notification',department:'Police'},
  {code:'police-vacation-watch',category:'Police',title:'Vacation / Property Watch Request',department:'Police'},
  {code:'police-traffic-enforcement',category:'Police',title:'Traffic Enforcement Concern',department:'Police'},
  {code:'police-neighborhood-concern',category:'Police',title:'Neighborhood Police Concern',department:'Police'},
  {code:'police-off-duty-event',category:'Police',title:'Request Off-Duty Police for an Event',department:'Police'},
  {code:'police-community-event',category:'Police',title:'Request Police Community Engagement',department:'Police'},
  {code:'police-fingerprinting',category:'Police',title:'Fingerprinting / Background Service Request',department:'Police'},
  {code:'fire-anonymous-hazard-report',category:'Fire Department',title:'Report a Fire or Life-Safety Hazard',department:'Fire'},
  {code:'fire-hydrant-request',category:'Fire Department',title:'Fire Hydrant Request',department:'Fire'},
  {code:'fire-water-system-test-release',category:'Fire Department',title:'Water-Based Fire Protection System Test / Release',department:'Fire'},
  {code:'fire-performance-test-fee',category:'Fire Department',title:'Fire Performance Test / Fee Request',department:'Fire'},
  {code:'fire-equipment-registration',category:'Fire Department',title:'Fire Equipment Registration',department:'Fire'},
  {code:'fire-system-impairment',category:'Fire Department',title:'Fire Protection System Impairment Notification',department:'Fire'},
  {code:'fire-shop-drawing-review',category:'Fire Department',title:'Shop Drawing Review Application',department:'Fire'},
  {code:'fire-foster-home-inspection',category:'Fire Department',title:'Request a Foster Home Inspection',department:'Fire'},
  {code:'fire-report-copy',category:'Fire Department',title:'Request a Fire Report',department:'Fire'},
  {code:'fire-smoke-co-alarm',category:'Fire Department',title:'Request a Smoke or CO Alarm',department:'Fire'},
  {code:'fire-hazmat-property-records',category:'Fire Department',title:'Hazmat / Fire Inspection Property Records',department:'Fire'},
  {code:'fire-off-duty-event-staff',category:'Fire Department',title:'Hire Off-Duty EMTs or Firefighters',department:'Fire'},
  {code:'fire-truck-education',category:'Fire Department',title:'Request a Fire Truck or Fire Education Program',department:'Fire'},
  {code:'fire-station-tour',category:'Fire Department',title:'Request a Fire Station Tour',department:'Fire'},
  {code:'fire-inspection',category:'Fire Department',title:'Request a Fire Inspection',department:'Fire'},
  {code:'fire-reinspection',category:'Fire Department',title:'Request a Fire Reinspection',department:'Fire'},
  {code:'fire-permit',category:'Fire Department',title:'Fire Prevention Permit Request',department:'Fire'},
  {code:'fire-plan-review',category:'Fire Department',title:'Fire Prevention Plan Review',department:'Fire'},
  {code:'fire-special-event',category:'Fire Department',title:'Special Event Fire-Safety Review',department:'Fire'},
  {code:'fire-open-burning',category:'Fire Department',title:'Open Burning / Recreational Fire Inquiry',department:'Fire'},
  {code:'fire-key-box',category:'Fire Department',title:'Fire Department Key Box / Rapid Entry Request',department:'Fire'},
  {code:'fire-code-question',category:'Fire Department',title:'Fire Code Question',department:'Fire'},
  {code:'airport-lost-found',category:'Airport',title:'Airport Lost & Found Report',department:'Airport'},
  {code:'airport-noise-complaint',category:'Airport',title:'Aircraft Noise Complaint',department:'Airport'},
  {code:'airport-feedback',category:'Airport',title:'Airport Feedback / Customer Concern',department:'Airport'},
  {code:'airport-accessibility-accommodation',category:'Airport',title:'Airport Accessibility / Accommodation Request',department:'Airport'},
  {code:'airport-ada-titlevi-complaint',category:'Airport',title:'Airport ADA / Title VI Complaint',department:'Airport'},
  {code:'airport-parking-concern',category:'Airport',title:'Airport Parking Concern',department:'Airport'},
  {code:'airport-ground-transportation',category:'Airport',title:'Airport Ground Transportation Concern',department:'Airport'},
  {code:'airport-tour-request',category:'Airport',title:'Request an Airport Tour',department:'Airport'},
  {code:'airport-community-engagement',category:'Airport',title:'Airport Community Engagement Request',department:'Airport'},
  {code:'airport-app-account-support',category:'Airport',title:'CLT Airport App / Account Support',department:'Airport'},
  {code:'airport-public-records',category:'Airport',title:'Airport Public Records Request',department:'Airport'},
  {code:'airport-badging-credentialing',category:'Airport',title:'Airport Badging / Credentialing Request',department:'Airport'},
  {code:'airport-tenant-vendor-access',category:'Airport',title:'Airport Tenant / Vendor Access Request',department:'Airport'},
  {code:'airport-construction-coordination',category:'Airport',title:'Airport Construction / Permit Coordination',department:'Airport'},
  {code:'airport-commercial-vehicle',category:'Airport',title:'Airport Commercial Vehicle / Operator Request',department:'Airport'},
  {code:'airport-concessions-vendor',category:'Airport',title:'Airport Concessions / Vendor Inquiry',department:'Airport'},
  {code:'rental-registration',category:'Housing & Property',title:'Residential Rental Property Registration',department:'General'},
  {code:'right-of-way-sight-obstructions',category:'Streets',title:'Right of Way Sight Obstructions',department:'General'},
  {code:'residential-traffic-calming-devices',category:'Streets',title:'Residential Traffic Calming Devices',department:'General'},
  {code:'pothole-repair',category:'Streets',title:'Pothole Repair',department:'General'},
  {code:'basketball-goal-in-street',category:'Streets',title:'Basketball Goal in Street',department:'General'},
  {code:'sidewalk-bike-lane-roadway-obstruction',category:'Streets',title:'Sidewalk, Bike Lane, or Roadway Obstruction',department:'General'},
  {code:'illegal-parking-tractor-trailers-bike-lanes',category:'Streets',title:'Illegal Parking (Tractor Trailers/Bike Lanes)',department:'General'},
  {code:'streetlight-repair',category:'Street Lights',title:'Streetlight Repair',department:'General'},
  {code:'residential-street-light-request',category:'Street Lights',title:'Residential Street Light Request',department:'General'},
  {code:'new-traffic-signal-request',category:'Signals',title:'New Traffic Signal Request',department:'General'},
  {code:'traffic-signal-malfunctioning',category:'Signals',title:'Traffic Signal Malfunctioning',department:'General'},
  {code:'traffic-signal-timing',category:'Signals',title:'Traffic Signal Timing',department:'General'},
  {code:'street-sign-repair',category:'Signs',title:'Street Sign Repair',department:'General'},
  {code:'new-street-sign-request',category:'Signs',title:'New Street Sign Request',department:'General'},
  {code:'graffiti',category:'Neighborhoods',title:'Graffiti',department:'General'},
  {code:'signs-public-rights-of-way',category:'Neighborhoods',title:'Signs in Public Rights of Way',department:'General'},
  {code:'high-weeds-grass-junk',category:'Neighborhoods',title:'High weeds & grass, junk in yard, etc.',department:'General'},
  {code:'parking-on-lawn-business-hours',category:'Neighborhoods',title:'Parking on Lawn 8 am - 5 pm M-F',department:'General'},
  {code:'parking-on-lawn-after-hours',category:'Neighborhoods',title:'Parking on Lawn After Hours/Weekends',department:'General'},
  {code:'boarded-up-residential-structure',category:'Neighborhoods',title:'Boarded Up Residential Structure',department:'General'},
  {code:'homeless-support-outreach',category:'Neighborhoods',title:'Homeless Support Outreach',department:'General'},
  {code:'trees',category:'Landscape',title:'Trees',department:'General'},
  {code:'plant-new-street-tree',category:'Landscape',title:'Plant New Street Tree',department:'General'},
  {code:'transit-concern',category:'Transit',title:'Transit Concern',department:'General'},
  {code:'flooding-drainage-structure',category:'Drainage',title:'Flooding from a drainage structure',department:'General'},
  {code:'erosion-creek-storm-drain',category:'Drainage',title:'Erosion along a creek or storm drain',department:'General'},
  {code:'blockage-city-drainage-system',category:'Drainage',title:'Blockage in a city drainage system',department:'General'},
  {code:'pollution-creeks-ponds-lakes',category:'Drainage',title:'Pollution in creeks, ponds or lakes',department:'General'},
  {code:'zoning-enforcement-complaint',category:'Zoning',title:'Complaints for Enforcement',department:'General'},
  {code:'zoning-holds-release',category:'Zoning',title:'Holds Release Requests',department:'General'},
  {code:'zoning-property-question',category:'Zoning',title:'Zoning Questions About a Property',department:'General'},
  {code:'park-rec-service-request',category:'Park & Recreation',title:'Park & Rec Service Request',department:'General'},
  {code:'park-rec-refund-cancellation',category:'Park & Recreation',title:'Refund/Cancellation Request',department:'General'},
  {code:'new-sidewalk',category:'Sidewalks',title:'New Sidewalk',department:'General'},
  {code:'sidewalk-repair',category:'Sidewalks',title:'Sidewalk Repair',department:'General'},
  {code:'container-obstruction',category:'Sidewalks',title:'Container Obstruction',department:'General'},
  {code:'crosswalk-request',category:'Sidewalks',title:'Crosswalk Request',department:'General'},
  {code:'dead-animal-collection',category:'Animals',title:'Dead Animal Collection',department:'General'},
  {code:'found-animal',category:'Animals',title:'Found Animal',department:'General'},
  {code:'bulky-item-pickup',category:'Trash',title:'Schedule a Bulky Item Pickup',department:'General'},
  {code:'curb-it-pickup-day',category:'Trash',title:'Curb it! Pickup Day Inquiry',department:'General'},
];

export const serviceTitle=(code:string)=>serviceCatalog.find(x=>x.code===code)?.title??code;
